services:
  nats:
    container_name: nats-server-test
    image: nats
    ports:
      - "4222:4222"

  kafka:
    image: confluentinc/confluent-local:7.4.1
    hostname: kafka
    container_name: kafka
    ports:
      - "8082:8082"
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
