version: '3.8'

services:
  app:
    image: domainservice
    container_name: app
    build:
      context: domainservice
      dockerfile: Dockerfile-domainservice
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongo
    profiles: [local]

  gateway:
    image: gateway
    container_name: gateway
    build:
      context: gateway
      dockerfile: Dockerfile-gateway
    env_file:
      - .env
    ports:
      - "8080:8080"
    profiles: [local]

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    profiles: [local]

  nats:
    container_name: nats-server
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    profiles: [local, gh-actions]

  kafka:
    container_name: kafka
    image: confluentinc/confluent-local:7.4.1
    hostname: kafka
    ports:
      - "8082:8082"
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
    profiles: [local, gh-actions]

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8888:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: true
    profiles: [local]

volumes:
  mongo-data:
    driver: local
