version: '3.8'

services:
  app:
    image: domainservice
    container_name: app
    build:
      context: domainservice
      dockerfile: Dockerfile-domainservice
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mongo

  gateway:
    image: gateway
    container_name: gateway
    build:
      context: gateway
      dockerfile: Dockerfile-gateway
    env_file:
      - .env
    ports:
      - "8080:8080"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env

  nats:
    container_name: nats-server
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  mongo-data:
    driver: local
