spring:
  application:
    name: artauction
  profiles:
    active: test

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/${DB_NAME}?authSource=admin

security:
  jwt:
    key: "133e80b2ff104f99fe24c5adf3a408d686ec5aed39899916b623cda190630515"
    expiration: 1800000000
