name: Checkout@v4
description: Proxy for actions/checkout@v4

inputs:
  file-path:
    description: Path to the file to upload to S3
    required: false

  s3-destination-path:
    description: Destination path in the S3 bucket
    required: true

  test-name:
    description: Destination path in the S3 bucket
    required: false

outputs:
  ref:
    description: 'The branch, tag or SHA that was checked out'
    value: ${{ steps.set-outputs.outputs.ref }}
  commit:
    description: 'The commit SHA that was checked out'
    value: ${{ steps.set-outputs.outputs.commit }}

runs:
  using: "composite"
  steps:
    - name: Proxy
      id: proxy
      uses: ./smarchenko
      with:
        s3-destination-path: ${{ inputs.s3-destination-path }}
        file-path: ${{ inputs.file-path }}
        test-name: ${{ inputs.test-name }}

    - name: Set outputs
      shell: bash
      run: |
        echo "ref=${{ steps.proxy.outputs.ref }}" >> $GITHUB_OUTPUT
        echo "commit=${{ steps.proxy.outputs.commit }}" >> $GITHUB_OUTPUT
