spring:
  application:
    name: artauction
  profiles:
    active: local
  main:
    web-application-type: reactive
  kafka:
    bootstrap-servers: "http://localhost:9092"

mongock:
  enabled: true
  migration-scan-package: ua.marchenko.artauction.common.mongock.migration

server:
  port: 8081

nats:
  uri: ${NATS_CONNECTION}
