apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: domainservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: general
              containerPort: 8081
              protocol: TCP
            - name: remotedebugging
              containerPort: 5005
              protocol: TCP
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: artauction-configmap
                  key: db-name
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: artauction-configmap
                  key: host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: artauction-configmap
                  key: port
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: artauction-configmap
                  key: java-opts
            - name: NATS_URI
              valueFrom:
                configMapKeyRef:
                  name: artauction-configmap
                  key: nats-uri
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: artauction-configmap
                  key: active-profile

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
