apiVersion: v1
kind: ConfigMap
metadata:
  name: artauction-configmap
data:
  db-name: "art"
  port: "27017"
  host: "mongodb-service"
  java-opts: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
