apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: "nginx"
  rules:
    - host: artauctionapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 8081
          - path: /api/v1/artworks
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 8080
