name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

env:
  gradle_cmd: ./gradlew --parallel --build-cache
    -PAWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
    -PAWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
    -Prepository=${{ secrets.PRIVATEMAVENREPO }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      issues: read
      pull-requests: write
      contents: read
      checks: write

    steps:      
      - name: Print commit message from CLI
        run: |
           COMMIT_SHA=${{ github.event.pull_request.head.sha }}
           commit_full=$(gh api repos/ajax-marchenko-s/ArtAuctionApp/commits/$COMMIT_SHA --jq '.')
           commit_message=$(gh api repos/ajax-marchenko-s/ArtAuctionApp/commits/$COMMIT_SHA --jq '.commit.message' | tr -d '\n')
           echo "commit-full=$commit_full"
           echo "commit-message=$commit_message"
        env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}





           
