name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

env:
  gradle_cmd: ./gradlew --parallel --build-cache
    -PAWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
    -PAWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
    -Prepository=${{ secrets.PRIVATEMAVENREPO }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      issues: read
      pull-requests: write
      contents: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Start docker container
        run: docker compose --profile gh-actions up -d

      - name: Run gradle build
        run: ${gradle_cmd} build

      - name: Run Delta Coverage check
        if: ${{ github.event_name == 'pull_request' && ( success() || failure() ) }}
        continue-on-error: ${{ contains(github.event.pull_request.labels.*.name, 'suppress-delta-coverage') }}
        run: ${gradle_cmd} deltaCoverage -PdiffBase="refs/remotes/origin/$GITHUB_BASE_REF"

      - name: Add Delta Coverage report
        if: ${{ github.event_name == 'pull_request' && ( success() || failure() ) }}
        continue-on-error: true
        uses: gw-kit/delta-coverage-plugin/actions/delta-coverage-report@2.4.0
        with:
          delta-coverage-report: build/reports/coverage-reports/delta-coverage/report.md

      - name: Add Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.15.1
        if: ${{ github.event_name == 'pull_request' && ( success() || failure() ) }}
        continue-on-error: true
        with:
          check_name: 'General Tests Report'
          files: '**/build/test-results/**/TEST-*.xml'

      - name: Print commit name
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"

      - name: Print commit hash
        run: |
          echo "Commit hash: ${{ github.event.head_commit.id }}"

      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"

      - name: Print commit message
        run: |
          SHA=${{ github.event.pull_request.head.sha }}
          MESSAGE=$(git log --format=%B -n 1 $SHA)
          echo "Commit Message: $MESSAGE"
      
      - name: List commits on the pull request
        run: |
          response=$(curl --request GET \
            --url 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits' \
            --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Content-Type: application/json')
          echo "$response" > response.json
          cat response.json

      - name: Get latest commit
        run: |
          echo "Get length of the array:"
          length=$(jq 'length' response.json)
          
          echo "Get index of the latest commit:"
          index=$(($length - 1))
          
          echo "Get context of the latest commit:"
          latest_commit=$(jq --argjson index $index '.[$index]' response.json)
          echo "$latest_commit"
          
          echo "Get commit message of the latest commit:"
          latest_commit_message=$(echo "$latest_commit" | jq -r '.commit.message')
          echo "$latest_commit_message"
          
          echo "Get commit SHA of the latest commit:"
          latest_commit_sha=$(echo "$latest_commit" | jq -r '.sha')
          echo "$latest_commit_sha"

      - name: Print commit message from cli
        run: |
          echo "Commit search result:"
          gh search commits --hash ${{ github.event.pull_request.head.sha }}
