name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Run gradle build
        run: ./gradlew build
