name: Playground for Svitlana Marchenko
run-name: SMarchenko Workflow experiments

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  test-gha:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: first step
        run: echo "This is first step"

      - name: my action
        uses: ./smarchenko-proxy
        with:
          s3-destination-path: 'test'

